### PR TITLE
search by keyword now works + nice keyboard sound effect added

### PR DESCRIPTION
**Pull request by Madoshakalaka**

### CODE REVIEW

**Comment by Madoshakalaka** [comment]
search logic: filter those books that either have query string in title or author

**Review by TheArcticGiraffe — COMMENTED** [review]
The searching by keyword seems to work really well. However, that keyboard noise is (while funny) annoying. If you remove that, I'll approve the merge.

**Comment by Madoshakalaka** [comment]
> The searching by keyword seems to work really well. However, that keyboard noise is (while funny) annoying. If you remove that, I'll approve the merge.

oh I thought that sound was adorable. I'll remove it though

**Comment by TheArcticGiraffe** [comment]
I tried to request a book, and I get the popup that the request has failed. Is that supposed to happen?

**Comment by Madoshakalaka** [comment]
> I tried to request a book, and I get the popup that the request has failed. Is that supposed to happen?

yes, if you request from your own books or the book is not available

**Review by wheredoesthisoceango — APPROVED** [review]
Seems good.

**Pull request merged**
